var buttonName_array = [
	'사람',		'외국인',			'가족',			'주택',			'방',
	'사업체',		'경제활동인',		'비경제활동인',		'사람의 체중',		'병상',		
	'응급실',		'수술',			'정신의학 처방',	'의료 노동자',		'조난당한 사람',	
	'구조대 노동자','범죄',			'경찰관',			'시내버스', 		'포장도로',
	'어린이집',	'초등학교 학급',	'고등학생',		'각급 교원',		'고등교육 대상자',
	'대학원생',	'시각예술활동',		'공연예술활동',		'특허등록',		'디자인등록',
	'소',		'닭',			'양식어류',		'곡식',			'과일·채소류',
	'산림',		'폐기물',			'산업폐수',		'하천',			'땅'
];


var unitWord_array = [
		'명','명','가구','채','개',
		'개','명','명','kg','병상',
		'개소','건','천건','명','명',
		'명','건','명','대','m',
		'개소','학급','명','명','명',
		'명','회','회','건','건',
		'마리','마리','천마리','톤','톤',
		'm³','톤(/1일)','m³(/1일)','m','m²'
	],
	unitWord_grdpUnit = '백만₩', 
	unitWord_grdpPerUnit = '₩';

function return_buttonName(_menuIndex) { return buttonName_array[_menuIndex]; }
function return_unitWord(_menuIndex) { return unitWord_array[_menuIndex]; }


var sentence_array = [
	"은 <br>인종, 성별, 국적, 종교, 직업 등과 무관하게 평등하다.",
	"은 <br>인종, 성별, 국적, 종교, 직업 등과 무관하게 평등하다.",
	"은 <br>가족구성, 거주지, 소득수준 등과 무관하게 평등하다.",
	"은 거주자가 인간답게 생활할 수 있는 <br>최소한의 환경조건을 갖춰야 한다.",
	"은 거주자가 인간답게 생활할 수 있는 <br>최소한의 환경조건을 갖춰야 한다.",
	"는 <br>규모, 업종, 창출하는 경제효과와 무관하게 평등하다.",
	"의 활동은 <br>그 종류와 상관없이 존중받아야 한다.",
	"의 활동은 <br>그 종류와 상관없이 존중받아야 한다.",
	"은 사람마다 고유해서 <br>특징으로서 인정받고 자의에 따라 유지되어야 한다.",
	"에는 <br>충분한 의료행위, 의료기기와 의약품이 제공되어야 한다.", 

	"은 모든 응급환자에게 <br>빠른 접근성과 충분한 의료시설을 보장해야 한다.",
	"이 안전하고 정확하게 진행되도록 <br>충분한 시간과 인력을 투입해야 한다.",
	"은 환자에 대한 오해와 편견없이 <br>필요한 약물을 적정하게 제공해야 한다.",
	"는 직종 및 과목에 상관없이 <br>의료노동에 대한 댓가를 충분히 보장받아야 한다.",
	"은 <br>신속하고 안전하게 구조될 권리를 가진다.",
	"는 <br>구조노동에 대한 충분한 댓가를 받을 권리를 가진다.",
	"마다 범인을 검거하도록 <br>충분한 수사역량을 투입해야 한다.",
	"은 <br>치안유지노동에 대한 충분한 댓가를 받을 권리가 있다.",
	"는 <br>모든 지역민의 이동권을 보장하도록 운영되어야 한다.",
	"는 <br>양질의 접근성과 노면상태를 유지해야 한다.",

	"은 <br>충분한 보육환경을 준비해야 한다.",
	"은 <br>적절한 학생수와 양질의 교육시설을 유지해야 한다.",
	"은 <br>충분한 교육과 양질의 지도를 받을 권리를 가진다.",
	"은 근무지, 직급, 과목에 상관없이<br>교육노동에 대한 충분한 댓가를 받을 권리를 가진다.",
	"는 전공이나 진로에 상관없이 <br>동등한 학생이자 사회구성원으로 대우받아야 한다.",
	"에게는 <br>양질의 연구노동환경과 충분한 노동의 댓가가 보장되어야 한다.",
	"이 양질의 경험을 제공하도록 <br>제작과정 및 전시에 충분한 자원을 제공해야 한다.",
	"이 양질의 경험을 제공하도록 <br>제작과정 및 공연에 충분한 자원을 제공해야 한다.",
	"은 <br>소중한 지식노동의 산물로서 존중받아야 한다.",
	"은 <br>소중한 예술노동의 산물로서 존중받아야 한다.",

	"는 사육되는 동안 <br>충분한 양분과 생활환경을 보장받아야 한다.",
	"은 사육되는 동안 <br>충분한 양분과 생활환경을 보장받아야 한다.",
	"는 양식되는 동안 <br>충분한 양분과 생활환경을 보장받아야 한다.",
	"이 병충해 없이 성장하도록 <br>충분히 보호하고 관리해야 한다.",
	"가 병충해 없이 성장하도록 <br>충분히 보호하고 관리해야 한다.",
	"이 생태계를 유지하도록 <br>충분한 보호와 관리를 제공해야 한다.",
	"을 <br>합당한 방법으로 수거하고 처리해야 한다.",
	"를 <br>충분히 정화하고 배출해야 한다.",
	"은 <br>맑게 유지될 권리를 가진다.",
	"은 <br>그 자체로 소중한 가치를 지닌다.",
], 
	staticsName_array = [
	"인구",
	"거주 외국인", 
	"가족", 
	"주택", 
	"주택에 속하는 방(2015)", 
	"등록사업체", 
	"경제활동인구(2017)", 
	"비경제활동인구(2017)", 
	"인구의 전체 체중(합산)", 
	"병원 입원실 병상(2015)", 

	"응급실", 
	"1년간 진행한 수술", 
	"1년간 향정신성의약품 처방", 
	"의료인력(의사, 치과의사, 한의사, 간호사, 약사, 물리치료사, 작업치료사, 사회복지사)", 
	"1년간 119구조대가 구조한 인원", 
	"119구조대 편성인원수", 
	"1년간 신고된 발생범죄", 
	"경찰청 및 해양경찰청 소속 경찰관(2015)", 
	"등록된 시내버스", 
	"포장도로 총연장",

	"어린이집", 
	"초등학교 학급", 
	"고등학생", 
	"유치원·초등학교·중학교·고등학교 교원", 
	"대학교 및 전문학교 재적생",
	"대학원 재적생",
	"1년간 진행된 시각예술활동(전시)", 
	"1년간 진행된 공연예술(국악, 양악, 연극, 무용, 혼합예술)활동", 
	"1년간 특허등록", 
	"1년간 디자인등록", 

	"사육 중인 한우·육우·젖소", 
	"사육 중인 닭", 
	"사육 중인 양식어류", 
	"1년간 생산된 식량작물(곡물)", 
	"1년간 생산된 과실 및 채소(과채, 엽채, 근채, 조미채소)류", 
	"임목축적(산림의 나무 전체 부피, 2015)",
	"1년간 일평균 생활폐기물, 사업장폐기물 및 건축폐기물 배출량", 
	"1년간 일평균 산업폐수 배출량(2015)", 
	"하천 총연장", 
	"행정구역 면적"
], 
	staticsCredit_phase1_array = [
	"행정안전부, 주민등록인구현황",
	"통계청, 인구총조사", 
	"행정안전부, 주민등록인구현황", 
	"통계청, 인구총조사", 
	"통계청, 주택총조사", 
	"통계청, 전국사업체조사", 
	"통계청, 경제활동인구조사", 
	"통계청, 경제활동인구조사", 
	"국민건강보험공단, 건강검진통계", 
	"행정안전부, 한국도시통계", 

	"국립중앙의료원, 응급의료현황통계", 
	"국민건강보험공단, 건강보험주요수술통계", 
	"건강보험심사평가원, 급여의약품청구현황", 
	"국민건강보험공단, 지역별의료이용통계", 
	"소방청, 119구조구급활동실적보고", 
	"소방청, 119구조구급활동실적보고", 
	"경찰청, 경찰청범죄통계", 
	"행정안전부, 한국도시통계", 
	"통계청, 운수업조사", 
	"국토교통부, 도로현황",

	"보건복지부, 어린이집및이용자통계", 
	"한국교육개발원, 교육기본통계", 
	"한국교육개발원, 교육기본통계", 
	"한국교육개발원, 교육기본통계", 
	"한국교육개발원, 교육기본통계",
	"한국교육개발원, 교육기본통계",
	"한국문화예술위원회, 문화예술활동현황조사", 
	"한국문화예술위원회, 문화예술활동현황조사", 
	"특허청, 지식재산권통계", 
	"특허청, 지식재산권통계", 

	"통계청, 가축동향조사", 
	"통계청, 가축동향조사", 
	"통계청, 어류양식동향조사", 
	"통계청, 농작물생산조사", 
	"통계청, 농작물생산조사", 
	"산림청, 산림기본통계",
	"환경부, 전국폐기물발생및처리현황", 
	"환경부, 산업폐수발생및처리현황", 
	"한국토지주택공사, 도시계획현황", 
	"국토교통부, 지적통계"
], 
	staticsCredit_phase2_array = [
	"행정구역(시군구)별/1세별 주민등록인구(2016)",
	"성 및 연령별 외국인-시도(2016)", 
	"행정구역(시군구)별 주민등록세대수(2016)", 
	"주택(오피스텔 포함)의 종류 및 주거면적별 가구(일반가구)(2016)", 
	"주택의 종류별/총방수별 주택-시군구(2015)", 
	"시도·산업별 사업체수, 종사자수 및 매출액(2016)", 
	"행정구역(시도)별 경제활동인구(2017)", 
	"행정구역(시도)별 경제활동인구(2017)", 
	"시도별 성별 연령별 평균 체중 분포 현황 : 일반, 생애(2016)", 
	"의료기관 및 병상수(2015)", 

	"응급의료기관 및 응급의료기관외 응급실 운영기관 수(시도별)(2016)", 
	"시도별 의료기관종별 수술 현황(계)(2016)", 
	"향정신성의약품 시도별 청구현황(건강보험)(2016)", 
	"시도별 의료인력 현황(2016)", 
	"시도별 구조활동 현황(2016)", 
	"구조대현황(2016)", 
	"[지역별]범죄 발생 및 검거 현황(2016)", 
	"경찰관수(2015)", 
	"시도별/산업별 총괄(2016)", 
	"시・도별 도로현황(2016)",

	"어린이집 현황(시·도)(2016)", 
	"초등학교 개황(2016)", 
	"고등학교 개황(2016)", 
	"유치원 개황", 
	"대학 개황",
	"대학원 개황(2016)",
	"17개 시도 예술 활동 현황(2016)", 
	"17개 시도 예술 활동 현황(2016)", 
	"시도별 등록(2016)", 
	"시도별 등록(2016)", 

	"축종별 시도별 농장수 및 마리수(2016 4/4분기)", 
	"닭 시도/사육규모별 가구수 및 마리수(2018 4/4분기)", 
	"시도·시군구별 양식현황 총괄(입식, 생산, 사육, 먹이(사료)를 준 량)(2016)", 
	"식량작물 생산량(정곡)(2016)", 
	"과실생산량", 
	"행정구역별 면적 및 축적(2015)",
	"폐기물 발생현황_생활폐기물", 
	"행정구역(시도,시군구)별 사업장수, 폐수 발생량, 폐수 방류량, 유기물질 부하량(2015)", 
	"하천(2016)", 
	"행정구역별・소유구분별 국토이용현황(2016)"
], 
	staticsCreditLink_array = [
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1B04006&conn_path=I2",
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1JA1502&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1B040B3&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1JC1521&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1PS1502&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1K52B08&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1DA7004S&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1DA7004S&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=350&tblId=DT_35007_N132&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=110&tblId=DT_11001N_2013_A042&conn_path=I2", 

	"http://kosis.kr/statHtml/statHtml.do?orgId=411&tblId=DT_41104_411&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=350&tblId=TX_35004_A003&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=354&tblId=DT_354004N_038&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=350&tblId=TX_35003_A003&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=156&tblId=TX_15602_A009&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=156&tblId=TX_15602_A000_2&conn_path=I2", 
	"http://www.police.go.kr/portal/main/contents.do?menuNo=200529", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=110&tblId=DT_11001N_2013_A051&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1I100001&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=116&tblId=DT_MLTM_962&conn_path=I2",

	"http://kosis.kr/statHtml/statHtml.do?orgId=117&tblId=DT_15407_NN003&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=334&tblId=DT_1963003_002&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=334&tblId=DT_1963003_004&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=334&tblId=DT_1963003_001&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=334&tblId=DT_1963003_013&conn_path=I2",
	"http://kosis.kr/statHtml/statHtml.do?orgId=334&tblId=DT_1963003_014&conn_path=I2",
	"http://kosis.kr/statHtml/statHtml.do?orgId=433&tblId=DT_433001N_1005&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=433&tblId=DT_433001N_1005&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=138&tblId=TX_13801_A047&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=138&tblId=TX_13801_A047&conn_path=I2", 

	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1EO200&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1EO061&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1EZ0007&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1ET0021&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1ET0292&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=136&tblId=DT_13601_A002&conn_path=I2",
	"http://kosis.kr/statHtml/statHtml.do?orgId=106&tblId=DT_106N_99_3300351&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=106&tblId=DT_106N_01_0100069&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=315&tblId=TX_315_2009_H1062&conn_path=I2", 
	"http://kosis.kr/statHtml/statHtml.do?orgId=116&tblId=DT_MLTM_5408&conn_path=I2"
]
	staticsCredit_phase3_array = [
	".",
	".", 
	".", 
	".", 
	". 최근집계시점인 2015년 통계 인용. \"총방수 7개 이상\" 주택은 7개로 환산해서 계산.", 
	".", 
	". 세종시 최초집계 시점인 2017년 통계 인용.", 
	". 세종시 최초집계 시점인 2017년 통계 인용.", 
	". 성별 평균 체중과 성별 주민등록인구를 곱한 값을 합산.", 
	". 최근집계시점인 2015년 통계 인용.", 

	".", 
	".", 
	" 및 <a href=\"http://kosis.kr/statHtml/statHtml.do?orgId=354&tblId=DT_354004N_066&conn_path=I2\" target=\"_blank\">향정신성의약품 성별/연령별 청구현황(의료급여)(2016)</a> 합산.", 
	".", 
	". 중앙구조대 제외. 창원시 소방본부는 경상남도에 합산.", 
	". 중앙구조대 제외. 경기도북부소방재난본부는 경기도에, 창원시 소방본부는 경상남도에 합산.", 
	". 경찰청(중앙) 및 해양안전본부 제외. 경기남부·북부지방경찰청은 경기도로 합산. 세종시는 <a href=\"http://www.cnpolice.go.kr/SEO/SJ/main.htm?Gubun=L05_03&kz=%BF%AC%B1%E2&kf1=sub&kf2=&kw=&bo=notify4&p=1&ku=25790&mo=v\" target=\"_blank\">&#8220;충남세종경찰서 범죄발생현황(2016)&#8221;</a> 통계에 포함되어, 충남·세종 통계에는 해당 숫자만큼 가감됨.", 
	". 최근집계시점인 2015년 통계 인용. 지역별 경찰청 및 해양경찰청 합산.", 
	". 시내버스 운송업 운송수단수 집계. 단, 세종시는 <a href=\"https://www.sejong.go.kr/prog/eBook/SE07/stat/sub03_01_01/list.do\" target=\"_blank\">&#8220;세종통계연보&#8221;(세종특별자치시, 2017년 발간, 2016년 기준)</a>의 &#8220;교통·관광 및 정보통신>업종별 운수업체&#8221; 집계 인용.", 
	".",

	".", 
	".", 
	".", 
	" / <a href=\"http://kosis.kr/statHtml/statHtml.do?orgId=334&tblId=DT_1963003_002&conn_path=I2\" target=\"_blank\">초등학교 개황</a> / <a href=\"http://kosis.kr/statHtml/statHtml.do?orgId=334&tblId=DT_1963003_003&conn_path=I2\" target=\"_blank\">중학교 개황</a> / <a href=\"http://kosis.kr/statHtml/statHtml.do?orgId=334&tblId=DT_1963003_004&conn_path=I2\" target=\"_blank\">고등학교 개황</a> (이상 2016). 각급학교 교원수 합산.", 
	" 및 <a href=\"http://kosis.kr/statHtml/statHtml.do?orgId=334&tblId=DT_1963003_011&conn_path=I2\" target=\"_blank\">전문대학 개황</a> (이상 2016). 각급 학교 재적학생수 합산.",
	".",
	".", 
	".", 
	".", 
	".", 

	".", 
	". 세종시 최초집계 시점인 2018년 1/4분기 통계 인용.", 
	".", 
	".", 
	" / <a href=\"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1ET0027&conn_path=I2\" target=\"_blank\">채소생산량(과채류)</a> / <a href=\"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1ET0028&conn_path=I2\" target=\"_blank\">채소생산량(엽채류)</a> / <a href=\"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1ET0029&conn_path=I2\" target=\"_blank\">채소생산량(근채류)</a> / <a href=\"http://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1ET0291&conn_path=I2\" target=\"_blank\">채소생산량(조미채소)</a>(이상 2016). 각 작물 생산량 합산.", 
	". 최근집계시점인 2015년 통계 인용.",
	" / <a href=\"http://kosis.kr/statHtml/statHtml.do?orgId=106&tblId=DT_106N_99_3300352&conn_path=I2\" target=\"_blank\">사업장생활계폐기물</a> / <a href=\"http://kosis.kr/statHtml/statHtml.do?orgId=106&tblId=DT_106N_99_3300002&conn_path=I2\" target=\"_blank\">사업장배출시설계폐기물</a> / <a href=\"http://kosis.kr/statHtml/statHtml.do?orgId=106&tblId=DT_106N_99_3300306&conn_path=I2\" target=\"_blank\">건설폐기물</a> (이상 2016). 각종 폐기물 발생량 합산.", 
	". 최근집계시점인 2015년 통계 인용.", 
	".", 
	"."
];